/**
 * Реестр серий: заготовки для src/content/series.
 */
export const SERIES = {
  tetris: { name: 'Тетрис', studio: 'vc-an-sssr', type: 'puzzle', summary: 'Головоломки Алексея Пажитнова: «Тетрис» 1984 года и его наследники Welltris и Faces, сделанные уже с «Докой».' },
  petka: { name: 'Петька и Василий Иванович', studio: 'skif', type: 'adventure', summary: 'Самый долгий сериал российских квестов: девять частей с 1998 по 2009 год о Петьке, Чапаеве, Анке и Фурманове, начатый S.K.I.F. и продолженный «Сатурн-плюс».' },
  allods: { name: 'Аллоды', studio: 'nival', type: 'rpg', summary: 'Фэнтезийный мир Nival: «Печать тайны», «Повелитель душ», «Проклятые земли» и онлайн-игра «Аллоды Онлайн», которая живёт до сих пор.' },
  dalnoboyshchiki: { name: 'Дальнобойщики', studio: 'softlab-nsk', type: 'simulation', summary: 'Три части симулятора грузоперевозок из Новосибирска: от гонок по трассам первой части до открытой России в третьей.' },
  perimeter: { name: 'Периметр', studio: 'kd-lab', type: 'strategy', summary: 'Стратегии K-D Lab о терраформировании и защитном поле: «Периметр» 2004 года, дополнение «Завет Императора» и «Периметр 2: Новая Земля».' },
  'space-rangers': { name: 'Космические рейнджеры', studio: 'elemental-games', type: 'rpg', summary: 'Живая галактика Elemental Games: «Космические рейнджеры», «Доминаторы» и переиздание HD: Революция.' },
  'kings-bounty': { name: 'King’s Bounty', studio: 'katauri', type: 'rpg', summary: 'Возрождённая Katauri классика 1990 года: «Легенда о рыцаре», «Принцесса в доспехах», «Перекрестки миров» и King’s Bounty II от 1C Entertainment.' },
  'il-2': { name: 'Ил-2 Штурмовик', studio: 'maddox-games', type: 'simulation', summary: 'Авиасимуляторы Второй мировой: от «Ил-2 Штурмовика» 2001 года и «Забытых сражений» до «Крылатых хищников» на приставках и «Великих сражений» 1C Game Studios.' },
  cossacks: { name: 'Казаки', studio: 'gsc-game-world', type: 'strategy', summary: 'Стратегии GSC о войнах XVII–XVIII веков с тысячами солдат на экране: «Казаки», «Казаки II» и «Казаки 3».' },
  stalker: { name: 'S.T.A.L.K.E.R.', studio: 'gsc-game-world', type: 'shooter', summary: 'Зона отчуждения GSC Game World: «Тень Чернобыля», «Чистое небо», «Зов Припяти» и вышедший через пятнадцать лет S.T.A.L.K.E.R. 2.' },
  metro: { name: 'Metro', studio: '4a-games', type: 'shooter', summary: 'Трилогия 4A Games по романам Дмитрия Глуховского о постъядерной Москве: Metro 2033, Last Light и Exodus.' },
  'men-of-war': { name: 'В тылу врага', studio: 'best-way', type: 'strategy', summary: 'Тактические стратегии Best Way на движке GEM: «В тылу врага», «В тылу врага 2» и международная линия Men of War.' },
  corsairs: { name: 'Корсары', studio: 'akella', type: 'rpg', summary: 'Пиратские ролевые игры «Акеллы» на движке Storm: от «Корсаров» 2000 года до фанатских «Возвращения легенды» и «Города потерянных кораблей».' },
  blitzkrieg: { name: 'Блицкриг', studio: 'nival', type: 'strategy', summary: 'Стратегии Nival о Второй мировой: «Блицкриг» 2003 года, десятки дополнений на движке Enigma и онлайн-«Блицкриг 3».' },
  'sudden-strike': { name: 'Sudden Strike', studio: 'fireglow', type: 'strategy', summary: 'Стратегии Fireglow о Второй мировой, известные в России как «Противостояние»: три части с 2000 по 2007 год.' },
  xenus: { name: 'Xenus', studio: 'deep-shadows', type: 'shooter', summary: 'Открытые миры Deep Shadows: «Xenus: Точка кипения» о Колумбии и «Xenus 2: Белое золото» о Карибах.' },
  'ex-machina': { name: 'Ex Machina', studio: 'targem', type: 'racing', summary: 'Постапокалипсис на колёсах от Targem: Ex Machina, дополнение «Меридиан 113», «Арена» и выросший из них онлайн-боевик Crossout.' },
  'alien-shooter': { name: 'Alien Shooter', studio: 'sigma-team', type: 'shooter', summary: 'Шутеры Sigma Team с видом сверху и тысячами монстров: Alien Shooter, Alien Shooter 2 и Zombie Shooter.' },
  'sherlock-holmes': { name: 'Шерлок Холмс', studio: 'frogwares', type: 'adventure', summary: 'Приключения Frogwares о великом сыщике: от «Загадки серебряной серёжки» до Chapter One и The Awakened.' },
  pathologic: { name: 'Мор', studio: 'ice-pick-lodge', type: 'adventure', summary: 'Театральные игры Ice-Pick Lodge о городе в степи, поражённом песочной язвой: «Мор. Утопия» 2005 года и «Мор» 2019-го.' },
  pathfinder: { name: 'Pathfinder', studio: 'owlcat', type: 'rpg', summary: 'Большие изометрические ролевые игры Owlcat по настольной системе Pathfinder: Kingmaker и Wrath of the Righteous.' },
  'world-of': { name: 'World of Tanks и семья', studio: 'wargaming', type: 'online', summary: 'Онлайн-игры Wargaming о технике XX века: World of Tanks, World of Warplanes, World of Warships и российский «Мир танков» от «Лесты».' },
  'shadow-fight': { name: 'Shadow Fight', studio: 'nekki', type: 'action', summary: 'Файтинги Nekki о бойцах-тенях: Shadow Fight 2 и 3, скачанные сотни миллионов раз.' },
  beholder: { name: 'Beholder', studio: 'warm-lamp', type: 'adventure', summary: 'Игры о слежке за жильцами в тоталитарном государстве: Beholder и Beholder 2 барнаульской Warm Lamp Games.' },
  'atom-rpg': { name: 'ATOM RPG', studio: 'atom-team', type: 'rpg', summary: 'Постъядерный СССР AtomTeam: ATOM RPG и его продолжение Trudograd.' },
  parkan: { name: 'Parkan', studio: 'nikita', type: 'action', summary: 'Космические боевики «Никиты» с полётами, высадками и стрельбой: «Хроника Империи» 1997 года, «Железная стратегия» и Parkan II.' },
  mekhanoidy: { name: 'Механоиды', studio: 'skyriver', type: 'rpg', summary: 'Ролевые боевики SkyRiver о разумных глайдерах на планете без людей: «Механоиды» и «Механоиды 2: Война кланов».' },
  knyaz: { name: 'Князь', studio: 'lesta', type: 'rpg', summary: 'Ролевые игры Lesta о Древней Руси: «Князь: Легенды Лесной страны» и «Князь 2: Кровь титанов».' },
  dcs: { name: 'DCS и Lock On', studio: 'eagle-dynamics', type: 'simulation', summary: 'Серьёзные авиасимуляторы Eagle Dynamics: «Су-27 Фланкер», Lock On: Modern Air Combat и платформа DCS World с модулями.' },
  scapes: { name: 'Игры Playrix', studio: 'playrix', type: 'puzzle', summary: 'Казуальные хиты Playrix: Fishdom, Township, Gardenscapes и Homescapes, объединённые механикой «три в ряд» и обустройством.' },
};
